[package]
name = "mcvm_shared"
version = "0.0.2"
edition = "2021"
license = "GPL"
description = "Shared libraries for mcvm"
authors = ["CarbonSmasher"]
keywords = ["minecraft", "launcher", "game", "mc"]
categories = ["games"]

[dependencies]
anyhow = "1.0.70"
serde = { version = "1.0.152", features = ["derive"] }
