[package]
name = "mcvm"
version = "0.5.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "A command-line Minecraft launcher for the future"
authors = ["CarbonSmasher"]
keywords = ["minecraft", "launcher", "game", "mc"]
categories = ["games"]

[lib]
name = "mcvm"
path = "src/lib.rs"

[workspace]
members = [
	"crates/mcvm_parse",
	"crates/mcvm_shared"
]

[profile.release]
lto = "thin"
strip = true

[dependencies]
anyhow = "1.0.70"
bytes = "1.4.0"
cfg-match = "0.2.1"
clap = { version = "4.1.13", features = ["derive"]}
color-print = "0.3.4"
directories = "5.0.0"
futures = "0.3.26"
itertools = "0.10.5"
libflate = "1.2.0"
mcvm_parse = { path = "crates/mcvm_parse", version = "0.0.8" }
reqwest = { version = "0.11.15", features = ["json", "rustls-tls"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
mcvm_shared = { path = "crates/mcvm_shared", version = "0.0.5" }
shellexpand = { version = "3.0.0", features = ["path"] }
tar = "0.4.38"
thiserror = "1.0.38"
tokio = { version = "1.25.0", features = ["macros", "fs", "rt-multi-thread"] }
zip = "0.6.4"
zip-extract = "0.1.2"
