[package]
name = "mcvm"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
cfg-match = "0.2.1"
color-print = "0.3.4"
curl = "0.4.44"
directories = "4.0.1"
libflate = "1.2.0"
phf = "0.11.1"
phf_macros = "0.11.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tar = "0.4.38"
thiserror = "1.0.38"
zip = "0.6.4"
