[package]
name = "mcvm"
version = "0.2.5"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
anyhow = "1.0.70"
bytes = "1.4.0"
cfg-match = "0.2.1"
clap = { version = "4.1.13", features = ["derive"]}
color-print = "0.3.4"
daemonize = "0.5.0"
directories = "5.0.0"
futures = "0.3.26"
itertools = "0.10.5"
libflate = "1.2.0"
openssl = "0.10.48"
phf = "0.11.1"
phf_macros = "0.11.1"
reqwest = { version = "0.11.15", features = ["blocking"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
sha1 = "0.10.5"
shellexpand = { version = "3.0.0", features = ["path"] }
tar = "0.4.38"
thiserror = "1.0.38"
tokio = { version = "1.25.0", features = ["macros", "fs"] }
zip = "0.6.4"
