[package]
name = "mcvm"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
color-print = "0.3.4"
curl = "0.4.44"
serde_json = "1.0.91"
thiserror = "1.0.38"
