name: Rust

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Make sure CLI is built
        run: cargo build -p mcvm_cli --release --verbose
      - uses: actions/upload-artifact@v4
        name: Upload CLI artifact
        with:
          name: ${{ matrix.os }}
          path: target/release/mcvm
