name: Rust

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --workspace --release --verbose
      - name: Run tests
        run: cargo test --workspace --verbose
      - name: Make sure CLI is built
        run: cargo build -p mcvm_cli --release --verbose
      - uses: actions/upload-artifact@v4
        name: Upload CLI artifact
        with:
          name: cli
          path: target/release/mcvm
